#!/usr/bin/env python3
"""Generate the Rust catalog from the checked-in AISC v16.0 numeric extract.

Normal generation/checking uses only the Python standard library. Importing the
pinned upstream workbook with --workbook additionally requires openpyxl.
"""

import argparse
from collections import Counter
import csv
from decimal import Decimal
import hashlib
import io
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data/aisc-v16.csv"
RUST_PATH = ROOT / "src/aisc/generated.rs"
WORKBOOK_SHA256 = "82d0ceb96a0d938ae1a6bd9637cb10a1e269225b5d668dce5b0bdc8d86013496"
FIELDS = "Type EDI_Std_Nomenclature AISC_Manual_Label W A d Ht OD bf B tw tf tnom tdes Ix Iy J".split()
COUNTS = {"WideFlange": 289, "SquareHollow": 126, "RectangularHollow": 399, "RoundHollow": 189}


def workbook_csv(path):
    """Read only the pinned workbook's US customary columns (A:CF)."""
    if hashlib.sha256(path.read_bytes()).hexdigest() != WORKBOOK_SHA256:
        raise ValueError("Workbook checksum differs from the pinned v16.0 source")
    from openpyxl import load_workbook

    workbook = load_workbook(path, read_only=True, data_only=True)
    rows = iter(workbook["Database v16.0"].values)
    header = next(rows)[:84]
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=FIELDS, lineterminator="\n")
    writer.writeheader()
    for values in rows:
        if values[0] not in ("W", "HSS"):
            continue
        source = dict(zip(header, values[:84]))
        writer.writerow({key: "" if source[key] == "–" else source[key] for key in FIELDS})
    workbook.close()
    return output.getvalue()


def number(row, name):
    """Validate finite positive source data and produce a Rust f64 literal."""
    value = Decimal(row[name])
    if not value.is_finite() or value <= 0:
        raise ValueError(f"Invalid {name} for {row['AISC_Manual_Label']}")
    literal = format(value, "f")
    return literal if "." in literal else literal + ".0"


def generate(source):
    """Validate names/geometry and emit one catalog entry per source row."""
    reader = csv.DictReader(io.StringIO(source))
    if reader.fieldnames != FIELDS:
        raise ValueError("Unexpected CSV schema")
    lines = [
        "// Generated by scripts/generate_aisc.py; do not edit.",
        "// Source: data/aisc-v16.csv; provenance and units: data/README.md.",
        "// Geometry: W [d, bf, tw, tf]; rectangular/square HSS [Ht, B, tnom, tdes];",
        "// round HSS [OD, OD, tnom, tdes]. Properties: [W, A, Ix, Iy, J].",
        "catalog! {",
    ]
    identifiers, aliases, counts = set(), {}, Counter()
    for row in reader:
        label, edi = row["AISC_Manual_Label"], row["EDI_Std_Nomenclature"]
        identifier = re.sub(r"[./-]", "_", label)
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", identifier) or identifier in identifiers:
            raise ValueError(f"Invalid or duplicate Rust identifier: {identifier}")
        identifiers.add(identifier)
        for alias in (label, edi):
            if not re.fullmatch(r"[A-Z0-9./-]+", alias):
                raise ValueError(f"Invalid designation: {alias}")
            if alias in aliases and aliases[alias] != identifier:
                raise ValueError(f"Ambiguous designation: {alias}")
            aliases[alias] = identifier
        if row["Type"] == "W":
            family, fields = "WideFlange", ["d", "bf", "tw", "tf"]
        elif row["Type"] == "HSS" and row["OD"]:
            family, fields = "RoundHollow", ["OD", "OD", "tnom", "tdes"]
        elif row["Type"] == "HSS":
            family = "SquareHollow" if Decimal(row["Ht"]) == Decimal(row["B"]) else "RectangularHollow"
            fields = ["Ht", "B", "tnom", "tdes"]
        else:
            raise ValueError(f"Unsupported family: {row['Type']}")
        geometry = [number(row, key) for key in fields]
        height, width, thickness1, thickness2 = map(Decimal, geometry)
        if family == "WideFlange":
            valid = thickness1 < width and 2 * thickness2 < height
        else:
            valid = thickness2 <= thickness1 and 2 * thickness1 < min(height, width)
        if not valid:
            raise ValueError(f"Invalid geometry: {label}")
        properties = [number(row, key) for key in ["W", "A", "Ix", "Iy", "J"]]
        counts[family] += 1
        lines.append(f'    {identifier} => ("{label}", "{edi}", {family}, [{", ".join(geometry)}], [{", ".join(properties)}]);')
    if counts != COUNTS:
        raise ValueError(f"Unexpected family counts: {dict(counts)}")
    return "\n".join(lines + ["}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if checked-in data/code differ")
    parser.add_argument("--workbook", type=Path, help="Re-extract the pinned upstream XLSX")
    args = parser.parse_args()
    source = workbook_csv(args.workbook) if args.workbook else CSV_PATH.read_text()
    generated = generate(source)
    if args.check:
        if CSV_PATH.read_text() != source or RUST_PATH.read_text() != generated:
            parser.exit(1, "AISC catalog is out of date; run scripts/generate_aisc.py\n")
        print("AISC catalog verified: 1003 sections")
    else:
        CSV_PATH.parent.mkdir(parents=True, exist_ok=True)
        RUST_PATH.parent.mkdir(parents=True, exist_ok=True)
        CSV_PATH.write_text(source)
        RUST_PATH.write_text(generated)
        print("Generated AISC catalog: 1003 sections")


if __name__ == "__main__":
    main()
